import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import localFont from '@next/font/local'
import NavBar from '../components/navbar'


const inter = Inter({ subsets: ['latin'] })

// const aswaq = localFont({
//   src: '../fonts/Aswaq-Regular.ttf',
// })

export const ManropeExtraBold = localFont({
  src: '../public/fonts/Manrope/Manrope-ExtraBold.otf',
  weight: '500'
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Tariq Achor Zyad</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/T.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navBar}>
            <NavBar></NavBar>
        </div>
        <div className={ManropeExtraBold.className}>
          <h1 className="text-dusty lg:xl:text-landingPageTitle text-5xl font-bold lg:xl:ml-24 ml-12 pt-2 lg:xl:mt-20 mt-12">Tariq<br/>Achor Zyad</h1>
          <h2 className="text-sandstone lg:xl:text-2xl text-lg font-bold lg:xl:ml-24 ml-12 pt-2 lg:xl:mt-4. mt-3 leading-relaxed">Hey, I'm a 3rd year Computer Science student at the University of Houston, <div className="text-dusty">Exploring the vast world of tech.</div></h2>
          {/* <h3 className="text-dusty lg:xl:text-6xl text-2xl font-extrabold lg:xl:ml-24 ml-12 pt-2 lg:xl:mt-6 mt-4">About Me</h3>
          <p className="text-sandstone lg:xl:text-xl lg:xl:ml-24 ml-12 pt-2 lg:xl:mt-4 mt-2 leading-relaxed"></p> */}

        </div>
      </main>
    </>
  )
}
